//! The generated shim crate: the build root for every editor-driven
//! extension dylib build.
//!
//! The shim lives in `.jackdaw/shim/` inside the user's project, is
//! regenerated whenever its inputs change, and is never edited by the
//! user. It depends on the user's crate by path and IS the dylib the
//! editor loads; the user's library rides inside it as an rlib. Making
//! the shim the build root is also what keeps the user's `Cargo.lock`
//! untouched: lockfile alignment operates on the shim's lock.
//!
//! The shim exports:
//!
//! * `jackdaw_extension_ctor()`: constructs the extension for the
//!   editor's in-process loader. Emitted when an extension type is
//!   configured.

use std::path::{Path, PathBuf};

/// What the shim must expose for one project. Derived from the
/// project's manifest and `jackdaw.toml` by the import/open flow.
pub struct ShimSpec {
    /// The user's Cargo package name, as spelled in its manifest
    /// (dashes preserved). The shim's path dependency keys on this.
    pub package_name: String,
    /// The user package's lib crate name (underscored). Code in the
    /// shim references the user crate by this.
    pub crate_name: String,
    /// Absolute path to the user project root (the shim's path dep).
    pub project_root: PathBuf,
    /// Type implementing the editor extension trait, if any.
    pub extension_type: Option<String>,
}

/// Write (or refresh) the shim crate under `jackdaw_dir` and return
/// its directory. Idempotent: files are only rewritten when content
/// changed, so an unchanged shim never invalidates cargo's caches.
pub fn ensure_shim(spec: &ShimSpec, jackdaw_dir: &Path) -> std::io::Result<PathBuf> {
    let shim_dir = jackdaw_dir.join("shim");
    std::fs::create_dir_all(shim_dir.join("src"))?;
    write_if_changed(&shim_dir.join("Cargo.toml"), &manifest_source(spec))?;
    write_if_changed(&shim_dir.join("src/lib.rs"), &lib_source(spec))?;
    Ok(shim_dir)
}

/// The shim's `Cargo.toml`.
///
/// The project path is written as a TOML *literal* string (single
/// quotes). A Windows path is full of backslashes, and TOML's basic
/// strings treat those as escapes: `C:\Users\...` fails to parse with
/// "invalid hex value" at `\U`. Literal strings take the bytes as they
/// are. Project paths cannot contain a single quote on Windows and are
/// vanishingly unlikely to elsewhere.
fn manifest_source(spec: &ShimSpec) -> String {
    let dep_path = spec.project_root.display();
    let package_name = &spec.package_name;
    // The bevy requirement tracks the minor this jackdaw targets, so a
    // release bump cannot leave the shim asking for a bevy the SDK was
    // not built from.
    let bevy = crate::BEVY_VERSION;
    format!(
        r#"# Generated by jackdaw; do not edit. Regenerated on project open.
[package]
name = "jackdaw_shim"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
"{package_name}" = {{ path = '{dep_path}' }}
bevy = {{ version = "{bevy}", default-features = false }}
"#
    )
}

fn lib_source(spec: &ShimSpec) -> String {
    let mut out =
        String::from("// Generated by jackdaw; do not edit. Regenerated on project open.\n");
    if let Some(extension) = &spec.extension_type {
        let crate_name = &spec.crate_name;
        out.push_str(&format!(
            r#"
#[unsafe(no_mangle)]
pub fn jackdaw_extension_ctor() -> Box<dyn jackdaw_api::JackdawExtension> {{
    Box::new({crate_name}::{extension}::default())
}}
"#
        ));
    }
    out
}

/// The generated shim source, for tests in sibling modules that need to
/// assert what a spec compiles to.
#[cfg(test)]
pub(crate) fn lib_source_for_test(spec: &ShimSpec) -> String {
    lib_source(spec)
}

fn write_if_changed(path: &Path, contents: &str) -> std::io::Result<()> {
    if let Ok(existing) = std::fs::read_to_string(path)
        && existing == contents
    {
        return Ok(());
    }
    std::fs::write(path, contents)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extension_shim_exports_the_ctor() {
        let spec = ShimSpec {
            package_name: "my-ext".into(),
            crate_name: "my_ext".into(),
            project_root: PathBuf::from("/proj"),
            extension_type: Some("MyExtension".into()),
        };
        let lib = lib_source(&spec);
        assert!(lib.contains("jackdaw_extension_ctor"));
        assert!(lib.contains("my_ext::MyExtension"));
        assert!(!lib.contains("jackdaw_run_game"));
        assert!(!lib.contains("jackdaw_extract_schema"));
        let manifest = manifest_source(&spec);
        assert!(manifest.contains("\"my-ext\" = { path = '/proj' }"));
    }

    #[test]
    fn a_game_only_spec_emits_an_empty_shim_lib() {
        let spec = ShimSpec {
            package_name: "my-game".into(),
            crate_name: "my_game".into(),
            project_root: PathBuf::from("/proj"),
            extension_type: None,
        };
        let lib = lib_source(&spec);
        assert!(!lib.contains("jackdaw_run_game"));
        assert!(!lib.contains("jackdaw_extract_schema"));
        assert!(!lib.contains("jackdaw_extension_ctor"));
    }

    /// A Windows project path is mostly backslashes, which TOML basic
    /// strings read as escapes. The generated manifest has to survive a
    /// real parse or every build on Windows dies inside a crate the user
    /// cannot see.
    #[test]
    fn a_windows_project_path_produces_parseable_toml() {
        let spec = ShimSpec {
            package_name: "my-game".into(),
            crate_name: "my_game".into(),
            project_root: PathBuf::from(r"C:\Users\joe\Projects\my-game"),
            extension_type: None,
        };
        let manifest = manifest_source(&spec);
        assert!(
            manifest.contains(r"path = 'C:\Users\joe\Projects\my-game'"),
            "expected a literal string, got:\n{manifest}"
        );
        toml::from_str::<toml::Value>(&manifest)
            .unwrap_or_else(|error| panic!("generated manifest must parse: {error}\n{manifest}"));
    }
}
