//! The generated shim crate: the build root for every editor-driven
//! project build.
//!
//! The shim lives in `.jackdaw/shim/` inside the user's project, is
//! regenerated whenever its inputs change, and is never edited by the
//! user. It depends on the user's crate by path and IS the dylib the
//! editor loads and the runner runs; the user's library rides inside
//! it as an rlib. Making the shim the build root is also what keeps
//! the user's `Cargo.lock` untouched: lockfile alignment operates on
//! the shim's lock.
//!
//! The shim exports plain-Rust entry symbols (host and dylib provably
//! share one ABI, so no C envelope and no version tags):
//!
//! * `jackdaw_run_game()`: builds the engine app (via the injected
//!   `jackdaw_api`), installs the project's game plugin, and runs it -
//!   all inside the dylib. Emitted when a game plugin is configured.
//! * `jackdaw_extension_entry(&mut ExtensionContext)`: registers
//!   editor extensions. Emitted when an extension type is configured.
//! * `jackdaw_extract_schema() -> *mut c_char`: reflects the project's
//!   types into schema JSON, inside the dylib. Always emitted, so the
//!   runner extracts the schema with a single FFI call and never links
//!   `bevy_reflect` itself.
//!
//! A project may export the entry symbols in any combination; game vs
//! extension is only which exist and which APIs they use.

use std::path::{Path, PathBuf};

/// What the shim must expose for one project. Derived from the
/// project's manifest and `jackdaw.toml` by the import/open flow.
pub struct ShimSpec {
    /// The user's Cargo package name, as spelled in its manifest
    /// (dashes preserved). The shim's path dependency keys on this.
    pub package_name: String,
    /// The user package's lib crate name (underscored). Code in the
    /// shim references the user crate by this.
    pub crate_name: String,
    /// Absolute path to the user project root (the shim's path dep).
    pub project_root: PathBuf,
    /// Fully-usable path of the game plugin type inside the user
    /// crate, e.g. `GamePlugin` or `game::MyPlugin`.
    pub game_plugin: Option<String>,
    /// Type implementing the editor extension trait, if any.
    pub extension_type: Option<String>,
}

/// Write (or refresh) the shim crate under `jackdaw_dir` and return
/// its directory. Idempotent: files are only rewritten when content
/// changed, so an unchanged shim never invalidates cargo's caches.
pub fn ensure_shim(spec: &ShimSpec, jackdaw_dir: &Path) -> std::io::Result<PathBuf> {
    let shim_dir = jackdaw_dir.join("shim");
    std::fs::create_dir_all(shim_dir.join("src"))?;
    write_if_changed(&shim_dir.join("Cargo.toml"), &manifest_source(spec))?;
    write_if_changed(&shim_dir.join("src/lib.rs"), &lib_source(spec))?;
    Ok(shim_dir)
}

/// The shim's `Cargo.toml`.
///
/// The project path is written as a TOML *literal* string (single
/// quotes). A Windows path is full of backslashes, and TOML's basic
/// strings treat those as escapes: `C:\Users\...` fails to parse with
/// "invalid hex value" at `\U`. Literal strings take the bytes as they
/// are. Project paths cannot contain a single quote on Windows and are
/// vanishingly unlikely to elsewhere.
fn manifest_source(spec: &ShimSpec) -> String {
    let dep_path = spec.project_root.display();
    let package_name = &spec.package_name;
    // The bevy requirement tracks the minor this jackdaw targets, so a
    // release bump cannot leave the shim asking for a bevy the SDK was
    // not built from.
    let bevy = crate::BEVY_VERSION;
    format!(
        r#"# Generated by jackdaw; do not edit. Regenerated on project open.
[package]
name = "jackdaw_shim"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
"{package_name}" = {{ path = '{dep_path}' }}
bevy = {{ version = "{bevy}", default-features = false }}
"#
    )
}

fn lib_source(spec: &ShimSpec) -> String {
    let mut out =
        String::from("// Generated by jackdaw; do not edit. Regenerated on project open.\n");
    // Every project shim exports the schema extractor. It reflects the
    // project's types inside the shim dylib (which shares the SDK's bevy),
    // so the runner only dlopens and calls it over FFI - it never links
    // bevy_reflect, whose generic statics cannot resolve in a Windows
    // binary. The caller owns and frees the returned C string.
    out.push_str(
        r#"
#[unsafe(no_mangle)]
pub extern "C" fn jackdaw_extract_schema() -> *mut std::os::raw::c_char {
    let json = jackdaw_api::__extract_project_schema_json();
    match std::ffi::CString::new(json) {
        Ok(c) => c.into_raw(),
        Err(_) => std::ptr::null_mut(),
    }
}
"#,
    );
    if let Some(plugin) = &spec.game_plugin {
        let crate_name = &spec.crate_name;
        out.push_str(&format!(
            r#"
#[unsafe(no_mangle)]
pub extern "C" fn jackdaw_run_game() {{
    jackdaw_api::__run_project_game(|app| {{
        app.add_plugins({crate_name}::{plugin});
    }});
}}
"#
        ));
    }
    if let Some(extension) = &spec.extension_type {
        let crate_name = &spec.crate_name;
        out.push_str(&format!(
            r#"
#[unsafe(no_mangle)]
pub fn jackdaw_extension_ctor() -> Box<dyn jackdaw_api::JackdawExtension> {{
    Box::new({crate_name}::{extension}::default())
}}
"#
        ));
    }
    out
}

/// The generated shim source, for tests in sibling modules that need to
/// assert what a spec compiles to.
#[cfg(test)]
pub(crate) fn lib_source_for_test(spec: &ShimSpec) -> String {
    lib_source(spec)
}

fn write_if_changed(path: &Path, contents: &str) -> std::io::Result<()> {
    if let Ok(existing) = std::fs::read_to_string(path)
        && existing == contents
    {
        return Ok(());
    }
    std::fs::write(path, contents)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn game_shim_exports_the_runner_entry() {
        let spec = ShimSpec {
            package_name: "my-game".into(),
            crate_name: "my_game".into(),
            project_root: PathBuf::from("/proj"),
            game_plugin: Some("GamePlugin".into()),
            extension_type: None,
        };
        let lib = lib_source(&spec);
        assert!(lib.contains("jackdaw_run_game"));
        assert!(lib.contains("jackdaw_api::__run_project_game"));
        assert!(lib.contains("my_game::GamePlugin"));
        assert!(!lib.contains("jackdaw_extension_ctor"));
        // The schema extractor is emitted for every project.
        assert!(lib.contains("jackdaw_extract_schema"));
        assert!(lib.contains("jackdaw_api::__extract_project_schema_json"));
        let manifest = manifest_source(&spec);
        // The path dep keys on the package name (dashes), while code
        // references the crate by its underscored name.
        assert!(manifest.contains("\"my-game\" = { path = '/proj' }"));
    }

    /// A Windows project path is mostly backslashes, which TOML basic
    /// strings read as escapes. The generated manifest has to survive a
    /// real parse or every build on Windows dies inside a crate the user
    /// cannot see.
    #[test]
    fn a_windows_project_path_produces_parseable_toml() {
        let spec = ShimSpec {
            package_name: "my-game".into(),
            crate_name: "my_game".into(),
            project_root: PathBuf::from(r"C:\Users\joe\Projects\my-game"),
            game_plugin: Some("GamePlugin".into()),
            extension_type: None,
        };
        let manifest = manifest_source(&spec);
        assert!(
            manifest.contains(r"path = 'C:\Users\joe\Projects\my-game'"),
            "expected a literal string, got:\n{manifest}"
        );
        toml::from_str::<toml::Value>(&manifest)
            .unwrap_or_else(|e| panic!("shim manifest must parse ({e}):\n{manifest}"));
    }

    #[test]
    fn ensure_shim_is_idempotent() {
        let dir = std::env::temp_dir().join("jackdaw_shim_test");
        let _ = std::fs::remove_dir_all(&dir);
        let spec = ShimSpec {
            package_name: "my-game".into(),
            crate_name: "my_game".into(),
            project_root: PathBuf::from("/proj"),
            game_plugin: Some("GamePlugin".into()),
            extension_type: None,
        };
        let shim = ensure_shim(&spec, &dir).unwrap();
        let manifest = shim.join("Cargo.toml");
        let first = std::fs::metadata(&manifest).unwrap().modified().unwrap();
        std::thread::sleep(std::time::Duration::from_millis(20));
        ensure_shim(&spec, &dir).unwrap();
        let second = std::fs::metadata(&manifest).unwrap().modified().unwrap();
        assert_eq!(first, second, "unchanged shim must not be rewritten");
    }
}
