use crate::parse::ast::{
    BsnAst, BsnExpr, BsnField, BsnNamedTuple, BsnPatch, BsnRelation, BsnStruct, BsnSymbol, BsnVar,
};
use crate::parse::lexer;
use bevy::ecs::entity::Entity;
use std::cell::RefCell;

grammar(ast: &RefCell<BsnAst>);

pub TopLevelPatches: Entity = {
    <p:Patch*> => ast.borrow_mut().create_patches(p),
}

pub Patches: Entity = {
    <p:Patch+> => ast.borrow_mut().create_patches(p),
};

pub Patch: Entity = {
    <n:Name> => ast.borrow_mut().create_name_patch(n),
    <b:Base> => ast.borrow_mut().create_patch(BsnPatch::Base(b)),
    <r:Relation> => ast.borrow_mut().create_patch(BsnPatch::Relation(r)),
    <a:"@"?> <s:Symbol> => ast.borrow_mut().create_patch(BsnPatch::Var(BsnVar(s, a.is_some()))),
    <a:"@"?> <s:Symbol> "{" <f:Fields> "}" => {
        ast.borrow_mut().create_patch(BsnPatch::Struct(BsnStruct(s, f, a.is_some())))
    },
    <a:"@"?> <s:Symbol> "(" <n:NamedTupleArgs> ")" => {
        ast.borrow_mut().create_patch(BsnPatch::NamedTuple(BsnNamedTuple(s, n, a.is_some())))
    },
};

Name: String = {
    "#" <i:"ident"> => i,
    "#" <s:"string_lit"> => s,
};

Base: String = {
    ":" <s:"string_lit"> => s,
};

Symbol: BsnSymbol = {
    <s:Symbol> "::" <n:"ident"> => s.append(n),
    <n:"ident"> => BsnSymbol::from_ident(n),
};

Fields: Vec<BsnField> = {
    => Vec::new(),
    <f:FieldsInner> ","? => f,
}

FieldsInner: Vec<BsnField> = {
    <t:Field> => { let mut v = Vec::new(); v.push(t); v },
    <h:FieldsInner> "," <t:Field> => { let mut h = h; h.push(t); h },
};

Field: BsnField = {
    <n:"ident"> ":" <e:Expr> => BsnField(n, e),
};

NamedTupleArgs: Vec<Entity> = {
    => Vec::new(),
    <n:NamedTupleArgsInner> ","? => n,
};

NamedTupleArgsInner: Vec<Entity> = {
    <t:Expr> => { let mut v = Vec::new(); v.push(t); v },
    <h:NamedTupleArgsInner> "," <t:Expr> => { let mut h = h; h.push(t); h },
};

Expr: Entity = {
    <a:"@"?> <s:Symbol> => ast.borrow_mut().create_expr(BsnExpr::Var(BsnVar(s, a.is_some()))),
    <a:"@"?> <s:Symbol> "{" <f:Fields> "}" => {
        ast.borrow_mut().create_expr(BsnExpr::Struct(BsnStruct(s, f, a.is_some())))
    },
    <a:"@"?> <s:Symbol> "(" <n:NamedTupleArgs> ")" => {
        ast.borrow_mut().create_expr(BsnExpr::NamedTuple(BsnNamedTuple(s, n, a.is_some())))
    },
    <s:"string_lit"> => ast.borrow_mut().create_expr(BsnExpr::StringLit(s)),
    <f:"float_lit"> => ast.borrow_mut().create_expr(BsnExpr::FloatLit(f)),
    <b:"bool_lit"> => ast.borrow_mut().create_expr(BsnExpr::BoolLit(b)),
    <i:"int_lit"> => ast.borrow_mut().create_expr(BsnExpr::IntLit(i)),
    "[" <n:NamedTupleArgsInner> ","? "]" => {
        ast.borrow_mut().create_expr(BsnExpr::List(n))
    },
    "[" "]" => {
        ast.borrow_mut().create_expr(BsnExpr::List(Vec::new()))
    },
};

Relation: BsnRelation = {
    <s:Symbol> "[" <r:Relations> "]" => BsnRelation(s, r),
};

Relations: Vec<Entity> = {
    => Vec::new(),
    <r:RelationsInner> ","? => r,
};

RelationsInner: Vec<Entity> = {
    <h:RelationsInner> "," <t:Patches> => { let mut h = h; h.push(t); h },
    <t:Patches> => { let mut v = Vec::new(); v.push(t); v },
};

extern {
    type Location = usize;
    type Error = lexer::Error;

    enum lexer::Token {
        "ident" => lexer::Token::Ident(<String>),
        "string_lit" => lexer::Token::StringLit(<String>),
        "float_lit" => lexer::Token::FloatLit(<f64>),
        "bool_lit" => lexer::Token::BoolLit(<bool>),
        "int_lit" => lexer::Token::IntLit(<i128>),
        "[" => lexer::Token::LBracket,
        "]" => lexer::Token::RBracket,
        "(" => lexer::Token::LParen,
        ")" => lexer::Token::RParen,
        "{" => lexer::Token::LBrace,
        "}" => lexer::Token::RBrace,
        "," => lexer::Token::Comma,
        ":" => lexer::Token::Colon,
        "#" => lexer::Token::Hash,
        "@" => lexer::Token::At,
        "::" => lexer::Token::DoubleColon,
    }
}
