//! Parser front-end for the `.bsn` scene format.
//!
//! This turns `.bsn` source text into a self-contained parser AST
//! ([`ast::BsnAst`]). It is the parse-only half of the format: it does not
//! resolve symbols to concrete component values. That resolution to ECS is
//! handled elsewhere.
//!
//! Parser vendored from Bevy's dynamic BSN work.

use std::cell::RefCell;

use bevy::ecs::{entity::Entity, prelude::Resource, world::World};
use lalrpop_util::lalrpop_mod;
use thiserror::Error;

pub mod ast;
pub mod lexer;

lalrpop_mod!(
    #[allow(
        clippy::all,
        clippy::pedantic,
        clippy::restriction,
        clippy::nursery,
        unused_qualifications,
        reason = "generated by lalrpop"
    )]
    grammar,
    "/parse/grammar.rs"
);

pub use ast::{
    BsnAst, BsnExpr, BsnField, BsnNameStore, BsnNamedTuple, BsnPatch, BsnPatches, BsnRelation,
    BsnStruct, BsnSymbol, BsnVar,
};

/// Identifies the root [`BsnPatches`] node inside a parsed [`BsnAst`]'s world.
///
/// Stored as a resource so the root stays reachable across the `BsnAst`
/// boundary without altering the vendored `BsnAst(World)` shape.
#[derive(Resource, Clone, Copy)]
pub struct BsnRoot(pub Entity);

/// An error produced while parsing `.bsn` source text.
#[derive(Error, Debug)]
pub enum ParseError {
    /// The lexer hit a character it could not turn into a token.
    #[error("lex error: unexpected character {0:?}")]
    Lex(char),
    /// The grammar rejected the token stream.
    #[error("parse error: {0}")]
    Parse(String),
    /// A struct gave the same field name twice.
    #[error("duplicate field '{field}' in '{type_name}'")]
    DuplicateField { type_name: String, field: String },
}

/// Reject structs that name the same field twice: applying such a patch
/// would silently let the last occurrence win, hiding hand-edit mistakes.
fn check_duplicate_fields(ast: &mut BsnAst) -> Result<(), ParseError> {
    fn find_duplicate(symbol: &ast::BsnSymbol, fields: &[ast::BsnField]) -> Option<ParseError> {
        let mut seen = std::collections::HashSet::new();
        for ast::BsnField(name, _) in fields {
            if !seen.insert(name.as_str()) {
                return Some(ParseError::DuplicateField {
                    type_name: symbol.1.clone(),
                    field: name.clone(),
                });
            }
        }
        None
    }

    let mut patches = ast.0.query::<&ast::BsnPatch>();
    for patch in patches.iter(&ast.0) {
        if let ast::BsnPatch::Struct(ast::BsnStruct(symbol, fields, _)) = patch
            && let Some(err) = find_duplicate(symbol, fields)
        {
            return Err(err);
        }
    }
    let mut exprs = ast.0.query::<&ast::BsnExpr>();
    for expr in exprs.iter(&ast.0) {
        if let ast::BsnExpr::Struct(ast::BsnStruct(symbol, fields, _)) = expr
            && let Some(err) = find_duplicate(symbol, fields)
        {
            return Err(err);
        }
    }
    Ok(())
}

/// Parse `.bsn` source text into a [`BsnAst`].
///
/// On success the returned AST holds every parsed node in its internal world,
/// with the root [`BsnPatches`] reachable via the entity returned by the
/// top-level parser.
pub fn parse_bsn(text: &str) -> Result<BsnAst, ParseError> {
    let mut world = World::new();
    world.init_resource::<BsnNameStore>();
    let ast = RefCell::new(BsnAst(world));

    let lexer = lexer::Lexer::new(text);
    match grammar::TopLevelPatchesParser::new().parse(&ast, lexer) {
        Ok(root) => {
            let mut ast = ast.into_inner();
            check_duplicate_fields(&mut ast)?;
            ast.0.insert_resource(BsnRoot(root));
            Ok(ast)
        }
        Err(err) => {
            if let lalrpop_util::ParseError::User {
                error: lexer::Error::UnexpectedChar(c),
            } = err
            {
                Err(ParseError::Lex(c))
            } else {
                Err(ParseError::Parse(format!("{err:?}")))
            }
        }
    }
}
